### ISSUE TITLE
gummo sapling placement fails

### ISSUE THREAD

**Issue by solstice-gw2** [koenvu/gw2nodes.com#1]
Hi Koenvu!

I love gw2nodes.com and try do my part to fill in where nodes are when I'm out on a gathering run.

Lately I've been doing more gathering runs in Kessex Hills because it's one of the only places to get Toxic Spore Seedlings which are used in popular raid consumables.

Anyway, I've noticed on more than one instance that the interface will allow me to select "Gummo Sapling", but when I try place it on the map, it doesn't actually save.  That's the only gathering node type I've noticed this happen for (there could be others, I've just noticed this one) -- I can place Iron, taproots, etc. and save them just fine.

Weird bug, but I thought I would let you know about it.

BTW, I use firefox, and this has been happening for a while (just never reported it before).  I'm currently using latest (52.0.2), but the problem has happened with older versions too.

IGN: solstice.1847

**Comment by koenvu** [comment]
Hi @solstice-gw2, thanks for your bug report!

I can't seem to reproduce it just yet. Next time this is happening, can you let me know the current time (+timezone) and the Server IP/name you are trying to add the sapling to?

**Comment by solstice-gw2** [comment]
Just tried again with the current build (cb9467c) and I'm still seeing the problem.

I tried to save a gummo sapling in the Diessa Plateau map for https://gw2nodes.com/?server=64.25.33.70 at exactly 3:14:55 UTC.  Clicked save and it did not save to the map.

I also verified that things like "Mimosa Sapling" can be saved in a Brisban Wildlands map, so it seems to be something particular to Gummo Sapling, not other types of soft wood.

**Comment by koenvu** [comment]
Thanks for your detailed report. I can see that a Gummo Sapling node was actually saved to the database at that time. Also, when I look at the map right now (in both Firefox and Safari) I can see two Gummo Saplings in Diessa Plateau on that server.

If you refresh the page manually after adding a Gummo Sapling, do the nodes appear, or do you just never see any Gummo Saplings?

When viewing this server: https://gw2nodes.com/?server=debug do you see the nodes arranged in a T as I placed them in the screenshot? Is it only happening in Firefox for you, or do you have another browser you can test with where it also happens?

<img width="974" alt="gw2nodes_-_node_locations" src="https://cloud.githubusercontent.com/assets/1215751/25083677/9fd77a36-2358-11e7-98a3-569606533bf2.png">

**Comment by solstice-gw2** [comment]
Well this is a very bizarre issue...

I'm on Windows 10 x86_64 with all recent updates.  If I start up Microsoft Edge (their new browser), I can see the Gummo saplings both on the map I mentioned in my previous comments and on the ?server=debug that you linked.

If I refresh either of those pages (even forcing a refresh with Shift + the refresh button), Firefox does not show them.

I thought it might be something weird with the extension AdBlock Plus (I've had it not show content before because of what it thought was an advertising id= in some HTML), so I've completely disabled AdBlock Plus, but that doesn't change anything.

Even when I restart Firefox with my (relatively few) add-ons disabled, the gummo saplings still don't show up.

However, if I have Firefox open the page in a "New Private Window", then the gummo saplings show up!

So, it's clearly not an issue with the site, it's some specific to my firefox not wanting to render them on the map unless it happens to be in a private browsing session.  This leads me to think it might be something with my browser's cache or something else related to that graphic or asset.

I'll do some more investigation and see if I can figure out what the problem might be.

Thanks

**Comment by koenvu** [comment]
Alright, keep me posted!

**Comment by solstice-gw2** [comment]
I tried a second browser cache clear and this one resolved the issue.  I must have had a corrupted version of that asset in my browser's cache, and it had been that way for months.

Sorry for the noise and thanks again for making gw2nodes.com

solstice.1847
